; CYD demo – TFT_eSPI (ILI9341_2) + XPT2046 touch. User_Setup.h v mapi projekta.
; Naloži na COM11: pio run -t upload

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Če COM5 ne deluje, spremeni na COM11 (ali pio device list za seznam portov)
upload_port = COM5
monitor_port = COM5

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    paulstoffregen/XPT2046_Touchscreen

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -I${PROJECT_DIR}
