; GRENSAN demo – ESP32 + TFT_eSPI + XPT2046, simulacija senzorjev (brez WiFi/MQTT)
; User_Setup.h v mapi firmware (po prvem buildu prepiši v .pio/libdeps/esp32dev/TFT_eSPI/)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Prilagodi COM portu (Device Manager)
upload_port = COM5
monitor_port = COM5

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    paulstoffregen/XPT2046_Touchscreen

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -I${PROJECT_DIR}
